name: Basic Go

on:
  workflow_call:
    inputs:
      go-versions:
        type: string
        # Arrays are currently not accepted:
        # https://github.com/orgs/community/discussions/11692
        default: "['1.19', '1.20', '1.x']"
      static-analysis-excludes-regex:
        type: string
      # TODO(wenvous): gofmt is harder to work with since it always recursively
      # formats files instead of restricting itself to just listed packages.
      # See if there is a way to have the same behaviour without relying on the
      # tool.
      tests-excludes-regex:
        type: string
        description: 'egrep regex for excluding certain packages from testing'
      race-tests-excludes-regex:
        type: string
        description: 'egrep regex for excluding certain packages from race testing, this is on top of packages excluded from regular testing'
      coverage-excludes-regex:
        type: string
        description: 'egrep regex for excluding certain packages from coverage reporting'
      skip-gofmt:
        type: boolean
      skip-govet:
        type: boolean
      skip-staticcheck:
        type: boolean
      skip-race-tests:
        type: boolean

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ${{ fromJson(inputs.go-versions) }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Build packages
        run: go build -v ./...

      - name: Run Tests
        run: |
          if [ -z "${{ inputs.tests-excludes-regex }}" ]; then
            echo "Running for all packages"
            go test -v ./...
          else
            echo "Running for non-excluded packages"
            go test -v $(go list ./... | egrep -v "${{ inputs.tests-excludes-regex }}")
          fi

      - name: Run race tests
        if: ${{ !inputs.skip-race-tests }}
        run: |
          if [ -z "${{ inputs.race-tests-excludes-regex }}" ]; then
            echo "Running for all packages"
            go test -race -v ./...
          else
            echo "Running for non-excluded packages"
            go test -race -v $(go list ./... | egrep -v "${{ inputs.tests-excludes-regex }}" | egrep -v "${{ inputs.race-tests-excludes-regex }}")
          fi

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Go Mod should be tidy
        run: |
          go mod tidy
          diff -u <(echo -n) <(git diff)

      - name: Go vet
        if: ${{ !cancelled() && !inputs.skip-govet }}
        run: |
          if [ -z "${{ inputs.static-analysis-excludes-regex }}" ]; then
            echo "Running for all packages"
            go vet ./...
          else
            echo "Running for non-excluded packages"
            go vet $(go list ./... | egrep -v "${{ inputs.static-analysis-excludes-regex }}")
          fi

      - name: revive
        if: ${{ !cancelled() }}
        run: |
          go install github.com/mgechev/revive@latest
          if [ -z "${{ inputs.static-analysis-excludes-regex }}" ]; then
            echo "Running for all packages"
            revive ./...
          else
            echo "Running for non-excluded packages"
            revive $(go list ./... | egrep -v ${{ inputs.static-analysis-excludes-regex }})
          fi

      - name: Gofmt
        if: ${{ !cancelled() && !inputs.skip-gofmt }}
        run: |
          diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run coverage
        # Always run unless manually cancelled.
        if: ${{ !cancelled() }}
        run: |
          if [ -z "${{ inputs.coverage-excludes-regex }}" ]; then
            echo "Running for all packages"
            go test -v -coverprofile=profile.cov ./...
          else
            echo "Running for non-excluded packages"
            go test -v -coverprofile=profile.cov $(go list ./... | egrep -v ${{ inputs.coverage-excludes-regex }})
          fi

      - name: Install goveralls
        if: ${{ !cancelled() }}
        run: go install github.com/mattn/goveralls@latest

      - name: Submit coverage
        if: ${{ !cancelled() }}
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github

      - name: Install staticcheck
        if: ${{ !cancelled() }}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Cache for staticcheck
        if: ${{ !cancelled() && !inputs.skip-staticcheck }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/staticcheck
            cache_folder=$(go env GOCACHE)
          key: ${{ github.job }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ github.job }}-${{ hashFiles('**/go.sum') }}

      - name: Staticcheck
        if: ${{ !cancelled() && !inputs.skip-staticcheck }}
        run: |
          if [ -z "${{ inputs.static-analysis-excludes-regex }}" ]; then
            echo "Running for all packages"
            staticcheck ./...
          else
            echo "Running for non-excluded packages"
            staticcheck $(go list ./... | egrep -v ${{ inputs.static-analysis-excludes-regex }})
          fi
